### ISSUE TITLE
Any Inference Example?

### ISSUE THREAD

**Issue by Drwaish** [Sllambias/yucca#178]
Can anyone share any sample file for inference and pre-train model?

Thanks

**Comment by Sllambias** [comment]
Hi Drwaish,

Thanks for your interest!

I'm afraid I can't share any real images but many are available by applying to e.g. https://sites.wustl.edu/oasisbrains/.
I can however supply a sample model trained on a subset of OASIS images through [zenodo](https://zenodo.org/records/13142948?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjdmZWZlY2QwLTgxYTMtNDU1MC05MTJiLTQzNDlkY2QzMmJhMiIsImRhdGEiOnt9LCJyYW5kb20iOiJlYTIzMzVkMmUyNzE3NWJlNzcyZWYwOWQ5NTc0YmQ3NSJ9.uVXEud9glp96p29dGjrtjEw0tRUEVaYc59wO9WDfjhawNik5K8_Us2TE9dUE67rK5L8yRDMDrr9vtZxpDujblg). 

When you've downloaded the modelzip, it needs to be unzipped in the yucca_models folder that you've also specified in the environment variables. After unzipping it should look like "YOUR/PATH/TO/YUCCA_DATA/yucca_models/Task001_OASIS/...."

Afterwards, assuming you've set up an environment for Yucca according to the instructions on the frontpage readme, you can run inference by using the following command:

```
yucca_inference -s Task001 -d 2D -t OUTPUT_NAME --pred YOUR/PATH/TO/IMAGEDIR
```

Best,
Sebastian

**Comment by Drwaish** [comment]
Answered by Author so issue closed.
Thanks
