### ISSUE TITLE
RFC: Thoughts about the `YuccaPlanner` abstraction

### ISSUE THREAD

**Issue by asbjrnmunk** [Sllambias/yucca#83]
This is a bit more long term, but think that the concept of a `plan` is difficult to understand for people approaching Yucca for the first time. 

**Problem**:

The planner and a plan to me refers to a series of actions that one wants to perform (which it also does). However:
1. It does not imply that it has anything to do with preprocessing.
2. It does not imply that it will also perform the sequence of actions in the plan.
3. It could be any series of actions, (for instance model training or dataset creation), while the `YuccaPlanner` is specialised to inspecting the data to make sure we perform adequate preprocessing. 

Further, a major source of confusion is that right now `yucca_planner` contains a `yucca_preprocessor` and not the other way around. A consequence of this, is that `yucca_planner` is the main api, and both preprocessor, trainer and inference scripts take a _planner_ argument when you want to change how the data has been _preprocessed_.

 _TLDR: I think the naming and the composition of abstractions ilogical and will be a major source of confusion for people starting out with yucca._ 

**Specific things I think we should change:**

1. Hierarchy of abstractions
I think that the preprocessor is the most basic abstraction which can then compose any modules or classes _it_ needs to perform the preprocessing, and i do not see the use of being able to combine arbitrary planners with arbitrary preprocessors. Thus, to me, we should only expose one ebstraction to the user, which could then produce artifacts used by e.g. inference. I think it is quite a bit clearer what happens when you call `yucca_train -p FancyPreprocessor` than `yucca_train -pl FancyPlanner`. 

2. Naming of abstractions
Again, the preprocessing abstraction is good, but to the planner abstraction just does not communicate what is actually happening. Right now it performs the actions: 
```
1. create dataset properties, 
2. determines spacing, 
3. determines target size from fixed size or spacing, 
4. validates target size, 
5. persists this information in a "plans" file.
```
**But, i do not think this is a plan!** It is metadata to be used when preprocessing, which is absolutely necessary for how the actions will be performed, but the actions are still in the preprocessor. I would suggest that we find another name, such as `DatasetInspector` or similar. Also, the plan is more of a `specification` than a `plan`.

**Comment by asbjrnmunk** [comment]
CC: @jakobamb @Sllambias

**Comment by Sllambias** [comment]
So the things you mention are certainly not exclusively things that could be considered planning/plans but all the other parts you don't mention are quite plan-y such as
1. what coordinate system are we going to work in?
2. will we crop?
3. what normalization operation do we intend to use?
4. how are we going to transpose things back and forth?

And yes there are some things that are not strictly plans, but these are part of a planner that, in the planning process, looks at the data to make informed decisions about the future plans which I think conceptually is quite coherent. The fact that it then saves this metadata in the plan is more of a QOL improvement. It can also still just be taken from the dataset_properties file.
