### ISSUE TITLE
Usability issue: "Exhausted other options: loading plans.json"

### ISSUE THREAD

**Issue by jakobamb** [Sllambias/yucca#99]
Currently, we print `Exhausted other options: loading plans.json`, every time we are not loading a plan from a checkpoint. I think this is confusing to a user, who likely does not have a mental model of the order in which plans are loaded and why. 

Not sure what the best solution is here, but if we do want this printed every time in the console, we should consider adding some more information, such as "No checkpoint file was provided, loading information for planning from the dataset plans.json" .... I hope you get the idea

referring to `yucca/training/configuration/configure_plans.py`:

```python
def load_plans(plans_path):
    # If plans is still none the ckpt files were either empty/invalid or didn't exist and we load the plans
    # from the preprocessed folder.
    print("Exhausted other options: loading plans.json")
    return load_json(plans_path)
```

**Comment by jakobamb** [comment]
The question that comes to mind as a user reading this is probably something like "Which options are exhausted, did something go wrong?"

**Comment by Sllambias** [comment]
You're right this is not very clear or intuitive. I will make a PR and make this more clear!
